spring.application.name=product
server.port=8089
#spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# SWAGGER DOCUMENTATION URL

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/api/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
